export const ROUTES = {
    HOME: '/',
    NOT_FOUND: '*',
    NOTIFICATIONS: '/notifications',
    OVERVIEW: '/overview',
    ABOUT: '/about',
    DISCOVER: '/discover',
    SALES: '/sales',
    PRODUCT_LIST: '/product-list',
    BILLING: '/billing',
    INVOICE: '/invoice',
    MESSAGES: '/messages',
    LOGIN: '/login',
    SIGNUP: '/signup',
    DOCS: '/docs',
    COMPONENTS: '/components',
    HELP: '/help',
    ADJUSTMENTS: '/adjustments',
    GLOBE: '/globe',
    COG: '/cog',
} as const;
